export const PRICE_ITEM_CLICK = 'PRICE_ITEM_CLICK';
export const REGION_ITEM_CLICK = 'REGION_ITEM_CLICK';
export const HOUSING_ITEM_CLICK = 'HOUSING_ITEM_CLICK';
export const STYLE_ITEM_CLICK = 'STYLE_ITEM_CLICK';
export const PRICE_CUSTOM = 'PRICE_CUSTOM';
