export const SEARCH_LIST_FETCHING = 'SEARCH_LIST_FETCHING';

export const SEARCH_LIST_FETCHEND = 'SEARCH_LIST_FETCHEND';

export const SEARCH_LOADMORE = 'SEARCH_LOADMORE';

export const HOT_KEY = 'HOT_KEY';